name: CI Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          "${GITHUB_WORKSPACE}/.github/install-deps-ubuntu.sh"
      - name: Build ahoviewer
        run: |
          meson setup build
          meson compile -C build
